version: 2.1
orbs:
  node: circleci/node@4.1.0
commands:
  start-dynamodb-local:
    description: Install DynamoDB Local and run in the background
    parameters:
      dest:
        type: string
        default: /tmp/dynamodb-local
    steps:
      - run:
          name: Install DynamoDB
          working_directory: << parameters.dest >>
          command: |
            sudo apt update
            sudo apt install -y openjdk-8-jre-headless
            curl -O https://s3.us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
            tar xzvf dynamodb_local_latest.tar.gz
      - run:
          name: Run DynamoDB
          working_directory: << parameters.dest >>
          background: true
          command: java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
jobs:
  lint:
    executor:
      name: node/default
      tag: "14.15"
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  test-unit:
    executor:
      name: node/default
      tag: "14.15"
    steps:
      - checkout
      - start-dynamodb-local
      - node/install-packages
      - run:
          name: Run tests
          environment:
            AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
            AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            AWS_DEFAULT_REGION: ddblocal
          command: npm run test
  build:
    executor:
      name: node/default
      tag: "14.15"
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"
  test-e2e:
    executor:
      name: node/default
      tag: << matrix.node_version >>
    working_directory: ~/e2e
    environment:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_DEFAULT_REGION: ddblocal
      AWS_PAGER: ""
    steps:
      - attach_workspace:
          at: ~/east-dynamodb
      - start-dynamodb-local
      - run:
          name: Install AWS CLI
          working_directory: /tmp
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Create database
          command: |
            aws dynamodb create-table \
              --table-name east-dynamodb-test \
              --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
              --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
              --billing-mode PAY_PER_REQUEST \
              --region ddblocal \
              --endpoint-url http://localhost:8000
      - run: cd ~/east-dynamodb && sudo npm link
      - run: npm init -y
      - run: "npm install 'east' '@aws-sdk/client-dynamodb@^3.3.0' '@aws-sdk/util-dynamodb@^3.3.0'"
      - run: npm link east-dynamodb
      - run: cp ~/east-dynamodb/.circleci/.eastrc ./.eastrc && cp -R ~/east-dynamodb/tests/migrations_default ./migrations
      - run: npx east migrate
      - run: npx east rollback
  publish:
    executor:
      name: node/default
      tag: "14.15"
    working_directory: ~/east-dynamodb
    steps:
      - attach_workspace:
          at: ~/east-dynamodb
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: npm publish
workflows:
  workflow:
    jobs:
      - lint
      - test-unit
      - build:
          requires:
            - lint
            - test-unit
      - test-e2e:
          requires:
            - build
          matrix:
            parameters:
              node_version: ["8.17", "10.23", "12.20", "14.15", "15.6"]
      - publish:
          requires:
            - test-e2e
          filters:
            tags:
              only: /v\d+\.\d+\.\d+.*/
